### ISSUE TITLE
Command `/wt` for teleporting to waypoint should not work when the user doesn't have `teleport` privileges

### ISSUE THREAD

**Issue by rodrigo-morales-1** [carloschon/simple_waypoints#1]
# What happens

A user without the privilege `teleport` can teleport to a waypoint by using the `/wt <waypoint-name>` command.

# What should happen

An error should be shown when a user without `teleport` tries to use the `/wt` command, just as the error that is shown by the built-in Minetest command `/teleport <x> <y> <z>`.

In Minetest version 5.9.1, the following error is shown when the user tries to call `/teleport <x> <y> <z>` and the user doesn't have the `teleport` privilege.

```
You don't have permission to run this command (missing privileges: teleport).
```

**Comment by carloschon** [comment]
I'm still on the fence about this one. I originally coded this for my kids but I guess it's bigger than that now. I'll update it in a couple of days. Thanks

**Comment by carloschon** [comment]
Closing this since the issue has been fixed in [this](https://github.com/carloschon/simple_waypoints/commit/9d4bcf56e3567df8eefca4b7d1cc0569b1face49) commit.
