### ISSUE TITLE
How to disable beam of light that points towards the sky when a waypoint is created?

### ISSUE THREAD

**Issue by rodrigo-morales-1** [carloschon/simple_waypoints#3]
When I create a waypoint, a beam of light pointing towards the sky is automatically created (see image below). I was wondering if it is possible to disable this behavior. That is, I don't want a beam of light to appear in all waypoints in the current map, I just want to see the name of the waypoint.

![image](https://github.com/user-attachments/assets/3c6dc3af-c70c-459f-a9c6-aef1fa904f43)

**Comment by carloschon** [comment]
Hi, Rodrigo. I'll post an update in a couple of days to solve this. I'll make the beacon optional via a toggle in the config. Thanks for your comment.

**Comment by carloschon** [comment]
The toggle is [here](https://github.com/carloschon/simple_waypoints/commit/9bffa6d5d084c523ff7739dcb2f81ab70eee34fd). Issue fixed!
